### ISSUE TITLE
Nail Down Images and Links

### ISSUE THREAD

**Issue by afoote31** [SimChid/comp-333-hw1#13]
We need to have 4 images and 4 links.

Links:
1. Link to sign up/in page (somewhere other than navbar)
2.
3.
4.

Images:
I think some clip-art type stuff like on Global Privacy Control could be good

Maybe let's first put the images/links as comments to this issue so that we have them all in one place?

**Comment by SimChid** [comment]
Image locations:

- Behind the slogan
- behind each point under "features"

**Comment by afoote31** [comment]
![image](https://github.com/SimChid/comp-333-hw1/assets/130381602/41a22834-9511-413d-9d7e-235910f6c3b3)
![image](https://github.com/SimChid/comp-333-hw1/assets/130381602/33df808d-87b6-4352-9996-be16ceadd1af)

**Comment by afoote31** [comment]
![image](https://github.com/SimChid/comp-333-hw1/assets/130381602/4e2ea53f-7ecb-474d-a221-b7abb28367b4)
![image](https://github.com/SimChid/comp-333-hw1/assets/130381602/e1090fe3-284f-4388-a131-689bc9ef84a0)

**Comment by SimChid** [comment]
We should make sure that these images are fine to use or if there are any copyright issues

**Comment by afoote31** [comment]
Alright these four are copyright free

![image](https://github.com/SimChid/comp-333-hw1/assets/130381602/c1d71f8e-6472-425f-b3e5-e9a119df1db7)
![image](https://github.com/SimChid/comp-333-hw1/assets/130381602/40424a6f-5d0d-431c-b453-b51a76f11b86)
![image](https://github.com/SimChid/comp-333-hw1/assets/130381602/37d03065-cd0f-40f5-9d8e-5c32dcdaf82f)
![image](https://github.com/SimChid/comp-333-hw1/assets/130381602/e606f5cd-82d8-44d5-a24b-5a2530761fe4)
